language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
before_script:
  - cp belbio_conf.yml.test belbio_conf.yml
  - cp belbio_secrets.yml.test belbio_secrets.yml
script:
  - make tests

after_success:
  - CODECLIMATE_REPO_TOKEN=yourtoken codeclimate-test-reporter
